services:
  base:
    image: my-python-app:latest
    command: ["make", "run"]
    ports:
      - 8080:8080
    networks:
      - shared_network2
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - .:/app

  rabbitmq:
    image: rabbitmq:3.8.6-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: gosdep
      RABBITMQ_DEFAULT_PASS: gosdep
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - shared_network2
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5

  worker:
    image: my-python-app:latest
    command: ["python3", "run.py", "worker"]
    networks:
      - shared_network2
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    deploy:
      replicas: 1
    volumes:
      - .:/app

  worker_low:
    image: my-python-app:latest
    command: ["python3", "run.py", "worker_low"]
    networks:
      - shared_network2
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    deploy:
      replicas: 1
    volumes:
      - .:/app

  worker_high:
    image: my-python-app:latest
    command: ["python3", "run.py", "worker_high"]
    networks:
      - shared_network2
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    deploy:
      replicas: 1
    volumes:
      - .:/app

  worker_outbox:
    image: my-python-app:latest
    command: ["python3", "run.py", "worker_outbox"]
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - shared_network2
    deploy:
      replicas: 1
    volumes:
      - .:/app


  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    container_name: postgres
    volumes:
      - pgdbdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - shared_network2
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  migrate:
    image: my-python-app:latest
    command: ["make", "migrate"]
    ports:
      - 2020:2020
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - shared_network2
    environment:
      - DB_HOST=postgres
      - DB_NAME=postgres
      - DB_USER=app
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - DATABASE_URL=postgresql+asyncpg://app:postgres@postgres:5432/postgres

volumes:
  pgdbdata:

networks:
  shared_network2:
    external: true
